#!/bin/bash
#
# Moving to new intranet server
# 09Sept2024.   tjones
#
# Transfer archive recordings to local archive server

if (( $(pgrep archive_rsync | wc -l)  > 2 ))
then
	echo $( pgrep archive_rsync | wc -l )
	echo "Rsync already running, exiting."
	exit 
fi 
echo "Rsync not running, proceeding..."

LOCAL_DIR="/data/aircheck/Complete Shows/"
REMOTE_DIR="/mnt/archive-local/aircheck/Complete Shows/"

TRANSFER_DIR="/data/aircheck/Old Archive Format/"
REMOTE_PUBLIC_DIR="/mnt/archive-local/aircheck/192k/"

# This will actually sync the complete shows
echo "Syncing complete shows..."
# Sync only files from the last day
find "$LOCAL_DIR" -mtime -1 -type f -printf '%f\n' > /var/tmp/filelist
rsync -vr --update --files-from=/var/tmp/filelist "$LOCAL_DIR" "$REMOTE_DIR"

echo "Syncing downsampled Otie format files..."
# Sync only files from the last day
find "$TRANSFER_DIR" -mtime -1 -type f -printf '%f\n' > /var/tmp/filelist
rsync -vr --update --files-from=/var/tmp/filelist "$TRANSFER_DIR" "$REMOTE_PUBLIC_DIR" 

