#!/bin/bash
# 
# Hacked 09Sept2024 to remove all traces of Spinitron finally.
# And to get this installed on the new server
# tjones
#
# Set paths and stuff
#
ARCHIVE_SCRIPT="/var/www/scripts/autoarchive"
SCRIPT_DIR="/var/www/scripts"
RECORDING_DIR="/data/aircheck/Complete Shows"
REMOTESTREAM="http://stream.wortfm.org:8000/ultra.mp3.m3u"
STREAM="http://localhost:8000/320k.mp3.m3u"
SHOWDB="/var/www/scripts/showdb.txt"
TRANSFER_DIR="/data/aircheck/Old Archive Format"
PADDING="120" # End padding in seconds
PUBLIC_BITRATE="192" # Bitrate for files for public archive
#
### We need to cache this Spinitron stuff for production version... 

# Look up old archive show name from database
DATE=$(date +%H:%M:%S)
DOW=$(date +%w)
string=$($SCRIPT_DIR/schedmap.pl $DATE $DOW)
IFS=$',\n'
read -r -a array  <<< "$string"

ShowName=${array[0]}
ShowID=${array[1]}
OldShowName=${array[2]}
ShowStartTime=${array[3]}
ShowStopTime=${array[4]}

#
# Populate start and stop times and convert to seconds;

STARTTIME=$(date +%H:%M:%S)
STOPTIME=$ShowStopTime
STARTSECS=$(date -d$STARTTIME +%s)
STOPSECS=$(date -d$STOPTIME +%s)

# If off air time is before on air time, we've crossed midnight,
# fix it by adding 24 hours in seconds:
if [ $STOPSECS -lt $STARTSECS ]
then
        STOPSECS=$(($STOPSECS + 86400))
fi

# Calculate runtime
RUNSECS=$(($STOPSECS - $STARTSECS + $PADDING))
echo "$RUNSECS"
ShowRunTime=$RUNSECS


# Look up old archive show name from database
DOW=$(date +%w)
ShowCode="$ShowID-$DOW"

# Build old filename format
OldShowName=$(awk "/^$ShowCode/ {print \$2}" $SHOWDB)
OldDate=$(date +"wort_%y%m%d_%H%M%S")
OldFilename=$(echo "$OldDate$OldShowName")

# Build record filename
Filename="FULL - $(date +"%F %H%M") - $(date +"%H%M" -d "+$ShowRunTime seconds") - $ShowName - $ShowCode - $OldFilename.mp3"

# Test to see if there's already a recording running - if so, quit. 
if [ -e "$RECORDING_DIR/$Filename" ]
then
	exit 1
fi

attime=$(date +%H:%M:00 -d $ShowStopTime)
# Schedule next recording - requires at 
if [ ! $(atq | grep $attime) ]
then
  at -f $ARCHIVE_SCRIPT $attime
fi

# Start recording current show from stream 
sox "$STREAM" -C 320 "$RECORDING_DIR/$Filename" trim 0 $ShowRunTime

# Convert to public bitrate and drop into the old archive transfer directory
sox "$RECORDING_DIR/$Filename" -C $PUBLIC_BITRATE "$TRANSFER_DIR/$OldFilename.mp3"

#
# Transfer to public server
#

# Remote SSH account
SSH_ACCOUNT="infotech@stream.wortfm.org"

#rsync to archive server:
archiveAccount="infotech@wortcast01.wortfm.org"
archiveDir="/var/www/html/mp3/"
# rsync -avz -e "ssh -i /home/infotech/.ssh/id_rsa" "$TRANSFER_DIR/$OldFilename.mp3" "$archiveAccount:$archiveDir"
